server:
  port: 9055

spring:


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  #== Thymeleaf 를 Module 에서 발견하기 위해서 아래와 같이 설정 ==#
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdetails-test;
    username: sa
    password:


  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true


  h2:
    console:
      enabled: true
      path: /h2-console
