server:
  port: 9057
  servlet:
    session:
      timeout: 60s

spring:
  #== Thymeleaf 를 Module 에서 발견하기 위해서 아래와 같이 설정 ==#
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/dev/temp/h2db/sessionmng;
    username: sa
    password:


  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console
